name: Generate Clients

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Name of the client'
        required: true
        default: 'latest'

permissions:
  contents: read

jobs:
  setup:
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ inputs.version }}
    steps:
      - name: Calculate version
        id: version
        run: |
          if [[ $VERSION == "latest" ]]; then
            VERSION=$(curl -s https://raw.githubusercontent.com/kaltura/server/HEAD/VERSION.txt)
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

  generate-clients:
    uses: kaltura-community/ci-pipelines/.github/workflows/build-artifact.yaml@dev
    needs: setup
    with:
      name: client-libs
      version: ${{ needs.setup.outputs.version }}
      dockerfile: ./tools/clients-generator.Dockerfile
      context: .

  release:
    runs-on: ubuntu-latest
    needs: [generate-clients, setup]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: client-libs-${{ needs.setup.outputs.version }}
          path: ./client-libs/
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: "Client Libs ${{ needs.setup.outputs.version }}"
          tag: client-libs-${{ needs.setup.outputs.version }}
          artifacts: ./client-libs/*.tar.gz
